import type { Entity } from './clients.types'

/**
 * Array de entidades mock para desenvolvimento e testes.
 *
 * Inclui obrigatoriamente os 4 registros exatos da referência visual
 * e cobre todos os valores de financialStatus e entityKind.
 *
 * Em produção, estes dados virão de /api/entities.
 */
export const entitiesMock: Entity[] = [
  // ── Os 4 registros exatos da referência visual ─────────────────────────────

  {
    id: 'ENT-0001',
    entityKind: 'cliente',
    name: 'Turbo Dynamics Inc.',
    subtitle: 'Large Fleet Enterprise',
    avatarIcon: 'enterprise',
    taxId: '12.345.678/0001-90',
    email: 'marcos.silva@turbo.com',
    phone: '+55 11 99876-5432',
    creditLimit: 42500,
    outstandingBalance: 0,
    financialStatus: 'ok',
    status: 'active',
  },
  {
    id: 'ENT-0002',
    entityKind: 'cliente',
    name: 'Juliana Mendes',
    subtitle: 'Individual / B2C',
    avatarIcon: 'person',
    taxId: '458.122.903-22',
    email: 'ju.mendes@gmail.com',
    phone: '+55 21 98822-1133',
    creditLimit: 2000,
    outstandingBalance: 1250,
    financialStatus: 'due',
    status: 'active',
  },
  {
    id: 'ENT-0003',
    entityKind: 'fornecedor',
    name: 'Global Logistics Hub',
    subtitle: 'Fleet Service Provider',
    avatarIcon: 'truck',
    taxId: '33.918.452/0001-08',
    email: 'ops@globalhub.com.br',
    phone: '+55 41 3344-0011',
    creditLimit: 150000,
    outstandingBalance: 0,
    financialStatus: 'credit_ok',
    status: 'active',
  },
  {
    id: 'ENT-0004',
    entityKind: 'cliente',
    name: 'Auto Fix Workshop',
    subtitle: 'Partner Garage',
    avatarIcon: 'tools',
    taxId: '08.221.445/0001-22',
    email: 'contact@autofix.net',
    phone: '+55 11 4004-9988',
    creditLimit: null,
    outstandingBalance: 0,
    financialStatus: 'prepaid',
    status: 'active',
  },

  // ── Clientes adicionais ────────────────────────────────────────────────────

  {
    id: 'ENT-0005',
    entityKind: 'cliente',
    name: 'Rápido Transportes Ltda.',
    subtitle: 'Regional Fleet Operator',
    avatarIcon: 'truck',
    taxId: '72.481.900/0001-55',
    email: 'frotas@rapidotransportes.com.br',
    phone: '+55 11 3333-7700',
    creditLimit: 85000,
    outstandingBalance: 0,
    financialStatus: 'ok',
    status: 'active',
  },
  {
    id: 'ENT-0006',
    entityKind: 'cliente',
    name: 'Carlos Eduardo Freitas',
    subtitle: 'Individual / B2C',
    avatarIcon: 'person',
    taxId: '321.654.987-11',
    email: 'carlos.freitas@email.com',
    phone: '+55 31 99100-2233',
    creditLimit: 3500,
    outstandingBalance: 3500,
    financialStatus: 'due',
    status: 'active',
  },
  {
    id: 'ENT-0007',
    entityKind: 'cliente',
    name: 'MegaPeças Distribuidora',
    subtitle: 'Large Auto Parts Distributor',
    avatarIcon: 'enterprise',
    taxId: '55.102.334/0001-77',
    email: 'comercial@megapecas.com.br',
    phone: '+55 11 2190-8800',
    creditLimit: null,
    outstandingBalance: 0,
    financialStatus: 'prepaid',
    status: 'active',
  },
  {
    id: 'ENT-0008',
    entityKind: 'cliente',
    name: 'Fernanda Oliveira',
    subtitle: 'Individual / B2C',
    avatarIcon: 'person',
    taxId: '098.765.432-10',
    email: 'fernanda.oliveira@gmail.com',
    phone: '+55 85 98765-0011',
    creditLimit: 1500,
    outstandingBalance: 0,
    financialStatus: 'credit_ok',
    status: 'inactive',
  },
  {
    id: 'ENT-0009',
    entityKind: 'cliente',
    name: 'Garagem Central SP',
    subtitle: 'Partner Garage',
    avatarIcon: 'tools',
    taxId: '19.837.204/0001-63',
    email: 'atendimento@garagemcentral.com.br',
    phone: '+55 11 5050-1122',
    creditLimit: 20000,
    outstandingBalance: 4800,
    financialStatus: 'due',
    status: 'active',
  },

  // ── Fornecedores adicionais ────────────────────────────────────────────────

  {
    id: 'ENT-0010',
    entityKind: 'fornecedor',
    name: 'NGK Spark Plugs Brasil',
    subtitle: 'OEM Parts Manufacturer',
    avatarIcon: 'enterprise',
    taxId: '60.812.942/0001-18',
    email: 'vendas@ngk.com.br',
    phone: '+55 11 3045-9900',
    creditLimit: 500000,
    outstandingBalance: 0,
    financialStatus: 'credit_ok',
    status: 'active',
  },
  {
    id: 'ENT-0011',
    entityKind: 'fornecedor',
    name: 'Bosch Auto Parts',
    subtitle: 'Global OEM Supplier',
    avatarIcon: 'enterprise',
    taxId: '59.104.422/0001-29',
    email: 'supply@bosch-autoparts.com.br',
    phone: '+55 41 3360-4455',
    creditLimit: 750000,
    outstandingBalance: 0,
    financialStatus: 'ok',
    status: 'active',
  },
  {
    id: 'ENT-0012',
    entityKind: 'fornecedor',
    name: 'Mahle Componentes Ltda.',
    subtitle: 'Engine Parts Supplier',
    avatarIcon: 'enterprise',
    taxId: '47.593.101/0001-44',
    email: 'compras@mahle.com.br',
    phone: '+55 19 3877-2200',
    creditLimit: 300000,
    outstandingBalance: 12000,
    financialStatus: 'due',
    status: 'active',
  },
  {
    id: 'ENT-0013',
    entityKind: 'fornecedor',
    name: 'Fremax Discos de Freio',
    subtitle: 'Brake Systems Supplier',
    avatarIcon: 'enterprise',
    taxId: '82.334.715/0001-91',
    email: 'pedidos@fremax.com.br',
    phone: '+55 47 3388-7711',
    creditLimit: null,
    outstandingBalance: 0,
    financialStatus: 'prepaid',
    status: 'active',
  },
  {
    id: 'ENT-0014',
    entityKind: 'fornecedor',
    name: 'Monroe Amortecedores',
    subtitle: 'Suspension Parts Supplier',
    avatarIcon: 'truck',
    taxId: '23.901.488/0001-07',
    email: 'logistica@monroe.com.br',
    phone: '+55 11 4002-7788',
    creditLimit: 200000,
    outstandingBalance: 0,
    financialStatus: 'credit_ok',
    status: 'active',
  },
  {
    id: 'ENT-0015',
    entityKind: 'fornecedor',
    name: 'SKF Rolamentos',
    subtitle: 'Bearings & Seals Supplier',
    avatarIcon: 'enterprise',
    taxId: '61.472.055/0001-33',
    email: 'contato@skf.com.br',
    phone: '+55 11 3030-5500',
    creditLimit: 180000,
    outstandingBalance: 5500,
    financialStatus: 'due',
    status: 'inactive',
  },
]
